-- ============================================================
--  SCM Pro — Full Schema (Phase 1 + 2 + 3)
--  기존 스키마 + Phase 2/3 신규 테이블 통합 버전
--  Supabase SQL Editor에서 실행하세요
-- ============================================================

-- ─────────────────────────────────────────
-- STEP 0: 기존 뷰 먼저 삭제 (FK 의존성 제거)
-- ─────────────────────────────────────────
DROP VIEW IF EXISTS v_forecast_weekly    CASCADE;
DROP VIEW IF EXISTS v_inventory_summary  CASCADE;
DROP VIEW IF EXISTS v_bom_detail         CASCADE;
DROP VIEW IF EXISTS v_parts_with_vendor  CASCADE;

-- 기존 테이블 역순 삭제 (CASCADE로 의존 오브젝트 함께 삭제)
DROP TABLE IF EXISTS forecast            CASCADE;
DROP TABLE IF EXISTS inventory           CASCADE;
DROP TABLE IF EXISTS bom                 CASCADE;
DROP TABLE IF EXISTS products            CASCADE;
DROP TABLE IF EXISTS parts               CASCADE;
DROP TABLE IF EXISTS vendors             CASCADE;
DROP TABLE IF EXISTS po_lines            CASCADE;
DROP TABLE IF EXISTS po_headers          CASCADE;
DROP TABLE IF EXISTS import_history      CASCADE;

-- Phase 2 / 3 신규 테이블도 정리
DROP TABLE IF EXISTS outbound_shipments  CASCADE;
DROP TABLE IF EXISTS workorders          CASCADE;
DROP TABLE IF EXISTS salesinvoices       CASCADE;
DROP TABLE IF EXISTS salesorders         CASCADE;

-- ============================================================
-- 1. VENDORS
-- ============================================================
CREATE TABLE vendors (
    vendor_code         TEXT PRIMARY KEY,
    vendor_name         TEXT NOT NULL,
    country             TEXT,
    address_line1       TEXT,
    address_line2       TEXT,
    city                TEXT,
    state_province      TEXT,
    postal_code         TEXT,
    country_full        TEXT,
    contact_name        TEXT,
    email               TEXT,
    phone               TEXT,
    fax                 TEXT,
    default_currency    TEXT DEFAULT 'USD',
    payment_terms       TEXT,
    incoterms           TEXT,
    bank_name           TEXT,
    bank_account        TEXT,
    swift_code          TEXT,
    iban                TEXT,
    remarks             TEXT,
    created_at          TIMESTAMPTZ DEFAULT NOW(),
    updated_at          TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- 2. PARTS
-- ============================================================
CREATE TABLE parts (
    part_no             TEXT PRIMARY KEY,
    part_name           TEXT NOT NULL,
    category            TEXT,
    in_out              TEXT CHECK (in_out IN ('in','out','')),
    material            TEXT,
    vendor_code         TEXT REFERENCES vendors(vendor_code),
    price               NUMERIC DEFAULT 0,
    currency            TEXT DEFAULT 'KRW',
    price_date          DATE,
    moq                 INTEGER DEFAULT 0,
    std_pack_size       INTEGER DEFAULT 0,
    leadtime_mp         INTEGER DEFAULT 0,
    leadtime_dev        INTEGER DEFAULT 0,
    incoterms           TEXT,
    shipping_method     TEXT,
    safety_stock        TEXT,
    hs_code             TEXT,
    unit                TEXT DEFAULT 'Pcs',
    remarks             TEXT,
    created_at          TIMESTAMPTZ DEFAULT NOW(),
    updated_at          TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- 3. PRODUCTS
-- ============================================================
CREATE TABLE products (
    part_no             TEXT PRIMARY KEY,
    kb_part_no          TEXT,
    car_code            TEXT,
    sub_code            TEXT,
    part_name           TEXT NOT NULL,
    customer            TEXT,
    type                TEXT DEFAULT 'mp' CHECK (type IN ('mp','dev')),
    price               NUMERIC DEFAULT 0,
    currency            TEXT DEFAULT 'USD',
    incoterms           TEXT,
    remarks             TEXT,
    created_at          TIMESTAMPTZ DEFAULT NOW(),
    updated_at          TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- 4. BOM
-- ============================================================
CREATE TABLE bom (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assy_part_no        TEXT NOT NULL REFERENCES products(part_no),
    part_no             TEXT NOT NULL REFERENCES parts(part_no),
    lr                  TEXT DEFAULT '-' CHECK (lr IN ('L','R','-')),
    qty                 NUMERIC NOT NULL DEFAULT 1,
    car_code            TEXT,
    sub_code            TEXT,
    remarks             TEXT,
    created_at          TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (assy_part_no, part_no, lr)
);

-- ============================================================
-- 5. INVENTORY
-- ============================================================
CREATE TABLE inventory (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_no             TEXT NOT NULL REFERENCES parts(part_no),
    location            TEXT NOT NULL CHECK (location IN ('onhand','intransit','vmi')),
    qty                 NUMERIC DEFAULT 0,
    warehouse           TEXT,
    eta                 DATE,
    po_no               TEXT,
    remarks             TEXT,
    last_updated        TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (part_no, location, po_no)
);

-- ============================================================
-- 6. FORECAST
-- ============================================================
CREATE TABLE forecast (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assy_part_no        TEXT NOT NULL REFERENCES products(part_no),
    customer            TEXT,
    year                INTEGER NOT NULL,
    week                INTEGER NOT NULL,
    week_key            TEXT NOT NULL,
    week_start_date     DATE,
    qty                 NUMERIC NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ DEFAULT NOW(),
    updated_at          TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (assy_part_no, year, week)
);

-- ============================================================
-- 7. PO HEADERS
-- ============================================================
CREATE TABLE po_headers (
    po_no               TEXT PRIMARY KEY,
    vendor_code         TEXT REFERENCES vendors(vendor_code),
    po_date             DATE NOT NULL DEFAULT CURRENT_DATE,
    currency            TEXT DEFAULT 'USD',
    incoterms           TEXT,
    payment_terms       TEXT,
    ship_to             TEXT,
    remarks             TEXT,
    status              TEXT DEFAULT 'draft' CHECK (status IN ('draft','issued','confirmed','partial','received','closed','cancelled')),
    created_by          TEXT,
    created_at          TIMESTAMPTZ DEFAULT NOW(),
    updated_at          TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- 8. PO LINES
-- ============================================================
CREATE TABLE po_lines (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_no               TEXT NOT NULL REFERENCES po_headers(po_no),
    line_no             INTEGER NOT NULL DEFAULT 1,
    part_no             TEXT NOT NULL REFERENCES parts(part_no),
    qty_ordered         NUMERIC NOT NULL DEFAULT 0,
    qty_received        NUMERIC DEFAULT 0,
    unit_price          NUMERIC DEFAULT 0,
    currency            TEXT,
    amount              NUMERIC GENERATED ALWAYS AS (qty_ordered * unit_price) STORED,
    required_date       DATE,
    eta                 DATE,
    remarks             TEXT,
    created_at          TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (po_no, line_no)
);

-- ============================================================
-- 9. IMPORT HISTORY
-- ============================================================
CREATE TABLE import_history (
    id                  TEXT PRIMARY KEY DEFAULT gen_random_uuid()::TEXT,
    imported_at         TIMESTAMPTZ DEFAULT NOW(),
    filename            TEXT,
    vendors_count       INTEGER DEFAULT 0,
    parts_count         INTEGER DEFAULT 0,
    products_count      INTEGER DEFAULT 0,
    bom_count           INTEGER DEFAULT 0,
    inventory_count     INTEGER DEFAULT 0,
    forecast_count      INTEGER DEFAULT 0,
    errors_count        INTEGER DEFAULT 0,
    status              TEXT DEFAULT 'success',
    imported_by         TEXT
);

-- ============================================================
-- 10. SALES ORDERS  ★ Phase 2
-- ============================================================
CREATE TABLE salesorders (
    id               TEXT PRIMARY KEY,
    so_number        TEXT UNIQUE NOT NULL,
    customer_po      TEXT,
    customer         TEXT,
    part_no          TEXT,
    qty              INTEGER DEFAULT 0,
    shipped_qty      INTEGER DEFAULT 0,
    unit_price       NUMERIC(14,4) DEFAULT 0,
    currency         TEXT DEFAULT 'USD',
    due_date         DATE,
    status           TEXT DEFAULT 'open',   -- open | shipped | invoiced | closed
    tracking_no      TEXT,
    remarks          TEXT,
    created_at       TIMESTAMPTZ DEFAULT NOW(),
    updated_at       TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- 11. SALES INVOICES  ★ Phase 2
-- ============================================================
CREATE TABLE salesinvoices (
    id               TEXT PRIMARY KEY,
    invoice_no       TEXT UNIQUE NOT NULL,
    so_numbers       TEXT,
    customer         TEXT,
    total_amount     NUMERIC(14,4) DEFAULT 0,
    currency         TEXT DEFAULT 'USD',
    issued_date      DATE,
    status           TEXT DEFAULT 'issued',  -- issued | paid | void
    created_at       TIMESTAMPTZ DEFAULT NOW(),
    updated_at       TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- 12. WORK ORDERS  ★ Phase 3
-- ============================================================
CREATE TABLE workorders (
    id               TEXT PRIMARY KEY,
    wo_number        TEXT UNIQUE NOT NULL,
    part_no          TEXT,
    qty              INTEGER DEFAULT 0,
    due_date         DATE,
    priority         TEXT DEFAULT 'medium',   -- high | medium | low
    status           TEXT DEFAULT 'planned',  -- planned | released | in_progress | completed | cancelled
    progress         INTEGER DEFAULT 0,
    mrp_ref          TEXT,
    remarks          TEXT,
    created_at       TIMESTAMPTZ DEFAULT NOW(),
    updated_at       TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- 13. OUTBOUND SHIPMENTS  ★ Phase 3
-- ============================================================
CREATE TABLE outbound_shipments (
    id               TEXT PRIMARY KEY,
    shipment_no      TEXT UNIQUE NOT NULL,
    so_number        TEXT,
    customer         TEXT,
    part_no          TEXT,
    shipped_qty      INTEGER DEFAULT 0,
    tracking_no      TEXT,
    ship_date        DATE,
    status           TEXT DEFAULT 'shipped',
    created_at       TIMESTAMPTZ DEFAULT NOW(),
    updated_at       TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- INDEXES
-- ============================================================
CREATE INDEX idx_parts_vendor_code     ON parts(vendor_code);
CREATE INDEX idx_parts_category        ON parts(category);
CREATE INDEX idx_products_customer     ON products(customer);
CREATE INDEX idx_products_type         ON products(type);
CREATE INDEX idx_bom_assy              ON bom(assy_part_no);
CREATE INDEX idx_bom_part              ON bom(part_no);
CREATE INDEX idx_inventory_part        ON inventory(part_no);
CREATE INDEX idx_inventory_location    ON inventory(location);
CREATE INDEX idx_forecast_assy         ON forecast(assy_part_no);
CREATE INDEX idx_forecast_week         ON forecast(year, week);
CREATE INDEX idx_po_lines_po           ON po_lines(po_no);
CREATE INDEX idx_po_lines_part         ON po_lines(part_no);
CREATE INDEX idx_workorders_status     ON workorders(status);
CREATE INDEX idx_salesorders_customer  ON salesorders(customer);
CREATE INDEX idx_salesorders_status    ON salesorders(status);

-- ============================================================
-- UPDATED_AT 자동 갱신 트리거
-- ============================================================
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER vendors_updated_at     BEFORE UPDATE ON vendors     FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER parts_updated_at       BEFORE UPDATE ON parts       FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER products_updated_at    BEFORE UPDATE ON products    FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER forecast_updated_at    BEFORE UPDATE ON forecast    FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER po_updated_at          BEFORE UPDATE ON po_headers  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER salesorders_updated_at BEFORE UPDATE ON salesorders FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER workorders_updated_at  BEFORE UPDATE ON workorders  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================
ALTER TABLE vendors           ENABLE ROW LEVEL SECURITY;
ALTER TABLE parts             ENABLE ROW LEVEL SECURITY;
ALTER TABLE products          ENABLE ROW LEVEL SECURITY;
ALTER TABLE bom               ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory         ENABLE ROW LEVEL SECURITY;
ALTER TABLE forecast          ENABLE ROW LEVEL SECURITY;
ALTER TABLE po_headers        ENABLE ROW LEVEL SECURITY;
ALTER TABLE po_lines          ENABLE ROW LEVEL SECURITY;
ALTER TABLE import_history    ENABLE ROW LEVEL SECURITY;
ALTER TABLE salesorders       ENABLE ROW LEVEL SECURITY;
ALTER TABLE salesinvoices     ENABLE ROW LEVEL SECURITY;
ALTER TABLE workorders        ENABLE ROW LEVEL SECURITY;
ALTER TABLE outbound_shipments ENABLE ROW LEVEL SECURITY;

-- 읽기/쓰기: 인증된 사용자 모두 허용
DO $$
DECLARE
    tbl TEXT;
BEGIN
    FOREACH tbl IN ARRAY ARRAY[
        'vendors','parts','products','bom','inventory','forecast',
        'po_headers','po_lines','import_history',
        'salesorders','salesinvoices','workorders','outbound_shipments'
    ] LOOP
        EXECUTE format(
            'CREATE POLICY "rw_authenticated" ON %I FOR ALL USING (auth.role() = ''authenticated'')',
            tbl
        );
    END LOOP;
END $$;

-- ============================================================
-- VIEWS
-- ============================================================

CREATE OR REPLACE VIEW v_parts_with_vendor AS
SELECT p.*, v.vendor_name, v.country AS vendor_country,
       v.contact_name AS vendor_contact, v.email AS vendor_email
FROM parts p LEFT JOIN vendors v ON p.vendor_code = v.vendor_code;

CREATE OR REPLACE VIEW v_bom_detail AS
SELECT b.id, b.assy_part_no, pr.part_name AS assy_name, pr.customer,
       b.part_no, pt.part_name, pt.vendor_code, v.vendor_name,
       b.lr, b.qty, pt.leadtime_mp, pt.moq, pt.price, pt.currency
FROM bom b
JOIN products pr ON b.assy_part_no = pr.part_no
JOIN parts    pt ON b.part_no      = pt.part_no
LEFT JOIN vendors v ON pt.vendor_code = v.vendor_code;

CREATE OR REPLACE VIEW v_inventory_summary AS
SELECT i.part_no, p.part_name, p.vendor_code, p.leadtime_mp, p.moq, p.safety_stock,
       SUM(CASE WHEN i.location = 'onhand'    THEN i.qty ELSE 0 END) AS qty_onhand,
       SUM(CASE WHEN i.location = 'intransit' THEN i.qty ELSE 0 END) AS qty_intransit,
       SUM(CASE WHEN i.location = 'vmi'       THEN i.qty ELSE 0 END) AS qty_vmi,
       SUM(i.qty) AS qty_total,
       MAX(CASE WHEN i.location = 'intransit' THEN i.eta END) AS next_eta
FROM inventory i JOIN parts p ON i.part_no = p.part_no
GROUP BY i.part_no, p.part_name, p.vendor_code, p.leadtime_mp, p.moq, p.safety_stock;

CREATE OR REPLACE VIEW v_forecast_weekly AS
SELECT f.year, f.week, f.week_key, f.week_start_date,
       f.assy_part_no, pr.part_name AS assy_name, f.customer, f.qty
FROM forecast f JOIN products pr ON f.assy_part_no = pr.part_no
ORDER BY f.year, f.week, f.assy_part_no;

-- ============================================================
-- PostgREST 스키마 캐시 리프레시
-- ============================================================
NOTIFY pgrst, 'reload schema';
